tasks:
  - name: terraform
    env:
       TF_LOG: DEBUG
    before: |
      cp $PROJECT_ROOT
      source ./bin/set_tf_alias
      source ./bin/install_terraform_cli 
      source ./bin/install_aws_cli
      source ./bin/generaate_tfrc_credentials 
      cp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
  - name: sinatra
    before: |
      cp $PROJECT_ROOT
      cd terratowns_mock_server 
      bundle install
      bundle exec ruby server.rb     
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cp $PROJECT_ROOT
      source ./bin/set_tf_alias
      source ./bin/install_terraform_cli
      source ./bin/install_aws_cli
      source ./bin/generaate_tfrc_credentials
  - name: http-server
    before: |
      cp $PROJECT_ROOT
      npm install --global http-server
    command: 
      http-server
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
    - phil294.git-log--graph
    - mhutchie.git-graph
    - phil294.git-log--graph

